// GET PRODUCT
export const GET_PRODUCT_PROCESS = "GET_PRODUCT_PROCESS"
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR"

// POST PRODUCT
export const POST_PRODUCT_PROCESS = "POST_PRODUCT_PROCESS"
export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS"
export const POST_PRODUCT_ERROR = "POST_PRODUCT_ERROR"

// UPDATE PRODUCT
export const UPDATE_PRODUCT_PROCESS = "UPDATE_PRODUCT_PROCESS"
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR"